### ISSUE TITLE
Not seeing translated text when i change language  to Arabic. 

### ISSUE THREAD

**Issue by sagargg** [FCSCOpendata/ckanext-fcscopendata#26]
## Description of BUG
When i change the language to Arabic. it is not showing translated text on pages. https://ckan.fcsc.develop.datopian.com/ar/

**Comment by sagargg** [comment]
@osahon-okungbowa  could you confirm if this is a bug?

**Comment by osahon-okungbowa** [comment]
@sagargg i confirm this behaves as you described. 

However, as long as the APIs for the Datasets and Resources contain the Arabic translations, we don't need to address this.

The client is going to you the ckan portal in English
