### ISSUE TITLE
Arabic pages width not fixed

### ISSUE THREAD

**Issue by MuhammadIsmailShahzad** [FCSCOpendata/ckanext-fcscopendata#30]
When I change the CKAN portal to arabic translated version the page is scrollable left and right. We need to fix that such that translated versions shows same page width as that of the English version.

![Screenshot from 2022-03-03 20-22-37](https://user-images.githubusercontent.com/57398621/156595321-4c4de9cc-07f2-4463-aa2a-78627280ae97.png)
## Acceptance

* [ ] Pages are of correct widht and are not scrollable left and right

## Tasks
* [ ] Debug
* [ ] Apply fix

**Comment by sagargg** [comment]
@MuhammadIsmailShahzad  it is showing fine in my machine/browser.
