### ISSUE TITLE
[Bug] Group hierarchy not working properly

### ISSUE THREAD

**Issue by gavram** [FCSCOpendata/ckanext-fcscopendata#54]
## Description

After I created group (themes) hierarchy (manually) some of the groups exist as parent group and as a child group at the same time. 

On the following screenshots you can see that `Disabilities` group is parent (the 1st image) and child (the 2nd image), too:

![image](https://user-images.githubusercontent.com/12686547/168091721-78e12f81-6cf8-459d-9ee6-e320c37e68de.png)

![image](https://user-images.githubusercontent.com/12686547/168091850-16fc197e-7806-4a8a-b49e-2dc8723e26f2.png)

When I visit that group from both links, I can see that it is the same group `Disabilities` which is a child of parent group `Social`

## Possible solutions

* [x] Solr re-indexing (done and not helped)
* [x] Check for duplicated values in `group` table in Postgresql CKAN DB (done, no duplicated values)
* [ ] ckanext-fcscsopendata extension

## Acceptance criteria

* [ ] creating a group hierarchy is not producing duplicated groups on parent and child levels

**Comment by osahon-okungbowa** [comment]
@sagargg please look into the code for theme hierarchy to resolve this

**Comment by sagargg** [comment]
**Fixed** with https://github.com/FCSCOpendata/ckanext-hierarchy/pull/2
